export const MockData = [
  {
    id: 1,
    name: "test name1",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user1", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 2,
    name: "test name2",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user2", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 3,
    name: "test name3",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user3", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 4,
    name: "test name4",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user4", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 5,
    name: "test name5",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user5", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 6,
    name: "test name6",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user6", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 7,
    name: "test name7",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user7", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 8,
    name: "test name8",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user8", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 9,
    name: "test name9",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user9", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 10,
    name: "test name10",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user10", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 11,
    name: "test name11",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user11", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 12,
    name: "test name12",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user12", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 13,
    name: "test name14",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user14", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 14,
    name: "test name14",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user14", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 15,
    name: "test name15",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user15", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 16,
    name: "test name16",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user16", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 17,
    name: "test name17",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user17", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 18,
    name: "test name18",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user18", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 19,
    name: "test name19",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user19", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 20,
    name: "test name20",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user20", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 21,
    name: "test name21",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user20", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 22,
    name: "test name22",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user20", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 23,
    name: "test name23",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user23", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 24,
    name: "test name25",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user25", avatar_url: "https://test-avatars.com" },
  },
  {
    id: 26,
    name: "test name26",
    html_url: "https://testing.com",
    description: "Lorem ipsum",
    owner: { login: "test-user26", avatar_url: "https://test-avatars.com" },
  },
];
